name: CI
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build]
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install javascript dependencies
      run: |
        npm install
    - name: Run tests
      run: |
        npm run test:unit
    - name: Run build
      run: |
        npm run generate
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
    - name: Deploy (prepare)
      if: github.ref == 'refs/heads/dev'
      run:
        rm dist/CNAME
    - name: Deploy (dev) 🚀
      if: github.ref == 'refs/heads/dev'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_NAME: humportal/humportal-dev
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
