name: CI
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install javascript dependencies
      run: |
        npm install
    - name: Run tests
      run: |
        npm run test:unit
    - name: Run build
      if: ${{ github.ref != 'refs/heads/dev' }}
      run: |
        npm run generate
    - name: Run build (dev)
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        npm run gen-subfolder
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
    - name: Deploy (prepare)
      if: github.ref == 'refs/heads/dev'
      run:
        rm dist/CNAME
    - name: Deploy (dev) 🚀
      if: github.ref == 'refs/heads/dev'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.HUMPORTAL_TOKEN }}
        repository-name: humportal/humportal-dev
        branch: gh-pages
        folder: dist
        clean: true
